### PR TITLE
Leaf/alimomennasab/download links

### PR DESCRIPTION
**Pull request by alimomennasab**

### CODE REVIEW

**Review by dal07065 — DISMISSED** [review]
Mostly just additions so shouldn't be an issue. Looks good to me 👍

**Review by misslame — CHANGES_REQUESTED** [review]
Dont merge in to main. 

Fix your conflicts first

@dal07065  don't approve PRs going to wrong branches or ones that have merge conflicts. It demonstrates you're not paying attention or you're not giving Ali your attention. Look at the commits in a PR. There should only be commits coming in from the requester. Additional commits should be questioned before a approval

**Comment by alimomennasab** [comment]
Corrected the branch of the merge. Also rechecked for any merging conflicts but couldn't find any (my branch only adds a few lines), so I will re-request a review.

**Review by dal07065 — APPROVED** [review]
I am only seeing additions pretty much so I don't see the issue here.

**Comment by misslame** [comment]
Thank you :D conflicts were on main. Thank tou for retargeting for proper branch. 

Always look at commits and the merge blocker messages.

**Review by misslame — APPROVED** [review]

**Pull request merged**
